"""add term registry

Revision ID: d170efcba567
Revises: d1e2f3a4b5c6
Create Date: 2025-12-24 16:53:03.867990

"""
from alembic import op
import sqlalchemy as sa



revision = 'd170efcba567'
down_revision = 'd1e2f3a4b5c6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('terms',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('canonical', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('term_type', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_terms_canonical'), 'terms', ['canonical'], unique=True)
    op.create_index(op.f('ix_terms_term_type'), 'terms', ['term_type'], unique=False)
    op.create_table('term_aliases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('alias', sa.String(length=100), nullable=False),
    sa.Column('term_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['term_id'], ['terms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_term_aliases_alias'), 'term_aliases', ['alias'], unique=True)
    op.create_index(op.f('ix_term_aliases_term_id'), 'term_aliases', ['term_id'], unique=False)
    op.create_table('term_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('event_type', sa.String(length=30), nullable=False),
    sa.Column('term_id', sa.Integer(), nullable=False),
    sa.Column('candidate_term_id', sa.Integer(), nullable=True),
    sa.Column('source_metadata', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_term_id'], ['terms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['term_id'], ['terms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_term_events_created_at'), 'term_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_term_events_event_type'), 'term_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_term_events_term_id'), 'term_events', ['term_id'], unique=False)
    op.create_index(op.f('ix_term_events_user_id'), 'term_events', ['user_id'], unique=False)
    op.create_table('prompt_term_links',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('prompt_id', sa.Integer(), nullable=False),
    sa.Column('term_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('intent', sa.String(length=20), server_default='coherent', nullable=False),
    sa.Column('role', sa.String(length=20), server_default='primary', nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['prompt_id'], ['suno_prompts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['term_id'], ['terms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prompt_id', 'term_id', name='uq_prompt_term_links_prompt_term')
    )
    op.create_index(op.f('ix_prompt_term_links_prompt_id'), 'prompt_term_links', ['prompt_id'], unique=False)
    op.create_index(op.f('ix_prompt_term_links_term_id'), 'prompt_term_links', ['term_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prompt_term_links_term_id'), table_name='prompt_term_links')
    op.drop_index(op.f('ix_prompt_term_links_prompt_id'), table_name='prompt_term_links')
    op.drop_table('prompt_term_links')
    op.drop_index(op.f('ix_term_events_user_id'), table_name='term_events')
    op.drop_index(op.f('ix_term_events_term_id'), table_name='term_events')
    op.drop_index(op.f('ix_term_events_event_type'), table_name='term_events')
    op.drop_index(op.f('ix_term_events_created_at'), table_name='term_events')
    op.drop_table('term_events')
    op.drop_index(op.f('ix_term_aliases_term_id'), table_name='term_aliases')
    op.drop_index(op.f('ix_term_aliases_alias'), table_name='term_aliases')
    op.drop_table('term_aliases')
    op.drop_index(op.f('ix_terms_term_type'), table_name='terms')
    op.drop_index(op.f('ix_terms_canonical'), table_name='terms')
    op.drop_table('terms')
    # ### end Alembic commands ###
