"""add prompt term link intent metadata

Revision ID: f4abd6464545
Revises: d170efcba567
Create Date: 2025-12-24 17:29:18.585848

"""
from alembic import op
import sqlalchemy as sa



revision = 'f4abd6464545'
down_revision = 'd170efcba567'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prompt_term_links', sa.Column('intent', sa.String(length=20), nullable=False))
    op.add_column('prompt_term_links', sa.Column('role', sa.String(length=20), nullable=False))
    op.add_column('prompt_term_links', sa.Column('confidence', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prompt_term_links', 'confidence')
    op.drop_column('prompt_term_links', 'role')
    op.drop_column('prompt_term_links', 'intent')
    # ### end Alembic commands ###
